/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.mtib.aoc23

import dev.mtib.aoc23.day.Day1
import dev.mtib.aoc23.utils.DayRunner

fun main(args: Array<String>) {
    val day = args.getOrNull(0)?.toInt() ?: 1

    println("Running day $day\n")

    val dayRunner = when (day) {
        1 -> Day1()
        else -> throw IllegalArgumentException("Day $day is not implemented yet.")
    } as DayRunner

    runPart(dayRunner, 1)
    runPart(dayRunner, 2)
}

private fun runPart(day: DayRunner, part: Int) {
    println("\u001b[1mPart $part:\u001b[0m")
    // time runtime
    val start = System.currentTimeMillis()
    when (part) {
        1 -> day.runPart1()
        2 -> day.runPart2()
        else -> throw IllegalArgumentException("Part $part is not a valid part.")
    }
    val end = System.currentTimeMillis()
    println("\u001b[36mRuntime: ${end - start}ms\u001b[0m\n")
}
